### ISSUE TITLE
typing external api of modules and asserting when running tests

### ISSUE THREAD

**Issue by jeromecovington** [hapijs/teamwork#14]
1) Touch `index.d.ts` to root of module.
2) Touch `assert-types.ts` in existing test directory.
3) Install `typescript` as a dev-dep.
4) (Optional) install `@typescript-eslint/eslint-plugin` & `@typescript-eslint/parser`.
5) Fill out types for public api in `index.d.ts`.
6) Add `"types": "index.d.ts"` to `package.json`
7) Fill out `assert-types.ts` to exercise public api (existing tests can be a guideline).
8) Add `"assert-types": "tsc --noEmit test/assert-types.ts"` to scripts in package.json
9) Include `npm run assert-types` to existing test flow for ci, et cetera.
10) Remember to add `index.d.ts` to the list of files included in `npm publish`.

**Comment by hueniverse** [comment]
Thanks!
