### ISSUE TITLE
Unexpected character '#' - index.js

### ISSUE THREAD

**Issue by wmkDev** [hapijs/teamwork#22]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise):  Community
* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: v12.13.1
* *module version*: "@hapi/teamwork": "4.x.x",
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): @hapi/nes
* *any other relevant information*:

#### How can we help?

I'm trying to use @hapi/nes but keep getting error trying to build it, and the error is about the use of "#" on the variables names on this package "@hapi/teamwork": "4.x.x", is that somehow allowed ?

```js
 ERROR  Failed to compile with 1 errors                                                                                                                  11:04:22 AM

 error  in ./node_modules/@hapi/teamwork/lib/index.js

Module parse failed: Unexpected character '#' (8:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| exports.Team = internals.Team = class {
| 
>     #meetings = null;
|     #count = null;
|     #notes = null;
```

**Comment by Marsup** [comment]
That's a sign you're not using node 12, double check that.

**Comment by wmkDev** [comment]
Yeap! thats correct, uninstalled and installed node 12.14.1 and it worked.

Thanks!
