### ISSUE TITLE
Strict mode

### ISSUE THREAD

**Issue by dominykas** [hapijs/teamwork#23]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: not relevant
* *module version*: latest
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): lab
* *any other relevant information*:

#### What problem are you trying to solve?

Would like to get notified when muda occurs and the team attends too many meetings (primarily in unit tests).

#### Do you have a new or modified API suggestion to solve the problem?

New option for constructor: `strict`. When `true`, `attend()` would throw.

**Comment by hueniverse** [comment]
I'll take a PR.
